services:
  - type: web
    name: agora
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    branch: main


