"""Initial

Revision ID: 6cd2eada0152
Revises: 
Create Date: 2025-07-30 20:29:59.770201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd2eada0152'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom_affiche', sa.String(length=80), nullable=False, server_default='temporaire'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('nom_affiche')

    # ### end Alembic commands ###
